<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GD0S75V" failures="21" tests="23" name="Surefire test" time="18.354" errors="0" timestamp="2023-05-17T12:47:59 GMT-07:00">
  <testcase classname="api.test.PetEndpointsTests" name="testAddPet" time="0.004"/>
  <testcase classname="api.test.PetEndpointsTests" name="testDeletePetById" time="0.0">
    <failure type="org.testng.TestNGException" message="
Cannot inject @Test annotated Method [testDeletePetById] with [int].
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection">
      <![CDATA[org.testng.TestNGException: 
Cannot inject @Test annotated Method [testDeletePetById] with [int].
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testDeletePetById -->
  <testcase classname="api.test.PetEndpointsTests" name="testGetPetById" time="0.0">
    <failure type="org.testng.TestNGException" message="
Cannot inject @Test annotated Method [testGetPetById] with [int].
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection">
      <![CDATA[org.testng.TestNGException: 
Cannot inject @Test annotated Method [testGetPetById] with [int].
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testGetPetById -->
  <testcase classname="api.test.PetEndpointsTests" name="testUpdatePet" time="0.002"/>
  <testcase classname="api.test.StoreEndpointsTests" name="testGetStoreInventory" time="3.961">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.StoreEndpointsTests.testGetStoreInventory(StoreEndpointsTests.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testGetStoreInventory -->
  <testcase classname="api.test.StoreEndpointsTests" name="testCreateOrder" time="1.016">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.StoreEndpointsTests.testCreateOrder(StoreEndpointsTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrder -->
  <testcase classname="api.test.StoreEndpointsTests" name="testCreateOrder" time="0.44">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.StoreEndpointsTests.testCreateOrder(StoreEndpointsTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrder -->
  <testcase classname="api.test.StoreEndpointsTests" name="testCreateOrder" time="0.434">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.StoreEndpointsTests.testCreateOrder(StoreEndpointsTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrder -->
  <testcase classname="api.test.StoreEndpointsTests" name="testCreateOrder" time="0.465">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.StoreEndpointsTests.testCreateOrder(StoreEndpointsTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrder -->
  <testcase classname="api.test.StoreEndpointsTests" name="testCreateOrder" time="0.5">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.StoreEndpointsTests.testCreateOrder(StoreEndpointsTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrder -->
  <testcase classname="api.test.StoreEndpointsTests" name="testCreateOrder" time="0.48">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.StoreEndpointsTests.testCreateOrder(StoreEndpointsTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrder -->
  <testcase classname="api.test.StoreEndpointsTests" name="testCreateOrder" time="0.491">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.StoreEndpointsTests.testCreateOrder(StoreEndpointsTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrder -->
  <testcase classname="api.test.StoreEndpointsTests" name="testCreateOrder" time="0.488">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.StoreEndpointsTests.testCreateOrder(StoreEndpointsTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrder -->
  <testcase classname="api.test.StoreEndpointsTests" name="testCreateOrder" time="0.508">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.StoreEndpointsTests.testCreateOrder(StoreEndpointsTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrder -->
  <testcase classname="api.test.StoreEndpointsTests" name="testCreateOrder" time="0.469">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.StoreEndpointsTests.testCreateOrder(StoreEndpointsTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testCreateOrder -->
  <testcase classname="api.test.StoreEndpointsTests" name="testGetOrderById" time="0.0">
    <failure type="org.testng.TestNGException" message="
Method public void api.test.StoreEndpointsTests.testGetOrderById(int) requires a @DataProvider named : orderId in class api.utility.Staticprovider">
      <![CDATA[org.testng.TestNGException: 
Method public void api.test.StoreEndpointsTests.testGetOrderById(int) requires a @DataProvider named : orderId in class api.utility.Staticprovider
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetOrderById -->
  <testcase classname="api.test.StoreEndpointsTests" name="testDeleteOrderById" time="0.0">
    <failure type="org.testng.TestNGException" message="
Method public void api.test.StoreEndpointsTests.testDeleteOrderById(int) requires a @DataProvider named : orderId in class api.utility.Staticprovider">
      <![CDATA[org.testng.TestNGException: 
Method public void api.test.StoreEndpointsTests.testDeleteOrderById(int) requires a @DataProvider named : orderId in class api.utility.Staticprovider
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteOrderById -->
  <testcase classname="api.test.UserEndpointsTests" name="testPostUser" time="0.639">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.UserEndpointsTests.testPostUser(UserEndpointsTests.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testPostUser -->
  <testcase classname="api.test.UserEndpointsTests" name="testGetUser" time="0.607">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.UserEndpointsTests.testGetUser(UserEndpointsTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testGetUser -->
  <testcase classname="api.test.UserEndpointsTests" name="testUpdateUser" time="0.048">
    <failure type="java.lang.IllegalArgumentException" message="Invalid number of path parameters. Expected 1, was 0. Undefined path parameters are: username.">
      <![CDATA[java.lang.IllegalArgumentException: Invalid number of path parameters. Expected 1, was 0. Undefined path parameters are: username.
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.RequestSpecificationImpl.assertCorrectNumberOfPathParams(RequestSpecificationImpl.groovy:1277)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1348)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
at io.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1161)
at io.restassured.internal.RequestSpecificationImpl.this$2$sendRequest(RequestSpecificationImpl.groovy)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1348)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)
at io.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:30)
at io.restassured.filter.Filter$filter.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at io.restassured.filter.Filter$filter$0.call(Unknown Source)
at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
at io.restassured.filter.time.TimingFilter.filter(TimingFilter.java:56)
at io.restassured.filter.Filter$filter$0.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at io.restassured.filter.Filter$filter.call(Unknown Source)
at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
at io.restassured.filter.FilterContext$next.call(Unknown Source)
at io.restassured.internal.filter.CsrfFilter.filter(CsrfFilter.groovy:70)
at io.restassured.filter.Filter$filter.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at io.restassured.filter.Filter$filter.call(Unknown Source)
at io.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:72)
at io.restassured.filter.FilterContext$next.call(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1704)
at io.restassured.internal.RequestSpecificationImpl.this$2$applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1348)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
at io.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1710)
at io.restassured.internal.RequestSpecificationImpl.this$2$applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1348)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1103)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1009)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:792)
at io.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:46)
at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:57)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
at io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy:180)
at io.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy)
at api.endpoints.UserEndpoints.updateUser(UserEndpoints.java:38)
at api.test.UserEndpointsTests.testUpdateUser(UserEndpointsTests.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 47 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUser -->
  <testcase classname="api.test.UserEndpointsTests" name="testDeleteUser" time="0.471">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.UserEndpointsTests.testDeleteUser(UserEndpointsTests.java:74)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.UserEndpointsTests" name="testLoginUser" time="0.472">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.UserEndpointsTests.testLoginUser(UserEndpointsTests.java:83)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testLoginUser -->
  <testcase classname="api.test.UserEndpointsTests" name="testLogoutUser" time="0.451">
    <failure type="java.lang.AssertionError" message="expected [500] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [500] but found [200]
at api.test.UserEndpointsTests.testLogoutUser(UserEndpointsTests.java:92)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- testLogoutUser -->
</testsuite> <!-- Surefire test -->
